name: CI WEB-ui - local

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."repo.internal:5000"]
              http = true
              insecure = true

      - name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: repo.internal:5000/webui:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect repo.internal:5000/webui:latest
